
-- 2024-12-22 17:01:46:
1014&1004
Query 1231 1194 statistics root@localhost db 1.4010ms 3.0000μs SELECT (SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Uptime') AS "Uptime" MAX(CASE WHEN Metric = 'Threads Connected' THEN Value END) AS "Threads Connected" MAX(CASE WHEN Metric = 'Ongoing Query Count' THEN Value END) AS "Ongoing Query Count" MAX(CASE WHEN Metric = 'Ongoing Select Count' THEN Value END) AS "Ongoing Select Count" MAX(CASE WHEN Metric = 'Ongoing Insert Count' THEN Value END) AS "Ongoing Insert Count" MAX(CASE WHEN Metric = 'Ongoing Update Count' THEN Value END) AS "Ongoing Update Count" MAX(CASE WHEN Metric = 'Ongoing Delete Count' THEN Value END) AS "Ongoing Delete Count" FROM ( SELECT 'Threads Connected' AS Metric VARIABLE_VALUE AS Value FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Threads_connected' UNION ALL SELECT 'Ongoing Query Count' AS Metric COUNT(*) AS Value FROM information_schema.processlist WHERE COMMAND <> 'Sleep' UNION ALL SELECT 'Ongoing Select
NO QUERY
945&935
Query 1232 1195 executing root@localhost db 1.5500ms 10.0000μs SELECT pps.PROCESSLIST_COMMAND AS command pps.THREAD_ID AS thd_id pps.PROCESSLIST_ID AS conn_id conattr_pid.ATTR_VALUE AS pid pps.PROCESSLIST_STATE AS state IF( (pps.NAME in ('thread/sql/one_connection' 'thread/thread_pool/tp_one_connection')) concat(pps.PROCESSLIST_USER '@' pps.PROCESSLIST_HOST) replace(pps.NAME 'thread/' '') ) AS user pps.PROCESSLIST_DB AS db pps.PROCESSLIST_INFO AS current_statement IF(isnull(esc.END_EVENT_ID) esc.TIMER_WAIT NULL) AS statement_latency esc.LOCK_TIME AS lock_latency IF(isnull(esc.END_EVENT_ID) esc.TIMER_WAIT 0) AS sort_time FROM performance_schema.threads pps LEFT JOIN performance_schema.events_statements_current esc ON (pps.THREAD_ID = esc.THREAD_ID) LEFT JOIN performance_schema.session_connect_attrs conattr_pid ON ( conattr_pid.PROCESSLIST_ID = pps.PROCESSLIST_ID AND conattr_pid.ATTR_NAME = '_pid' ) WHERE pps.PROCESSLIST_I
NO QUERY

-- 2024-12-22 17:02:13:
944&934
Query 1231 1194 executing root@localhost db 0.7310ms 4.0000μs SELECT pps.PROCESSLIST_COMMAND AS command pps.THREAD_ID AS thd_id pps.PROCESSLIST_ID AS conn_id conattr_pid.ATTR_VALUE AS pid pps.PROCESSLIST_STATE AS state IF( (pps.NAME in ('thread/sql/one_connection' 'thread/thread_pool/tp_one_connection')) concat(pps.PROCESSLIST_USER '@' pps.PROCESSLIST_HOST) replace(pps.NAME 'thread/' '') ) AS user pps.PROCESSLIST_DB AS db pps.PROCESSLIST_INFO AS current_statement IF(isnull(esc.END_EVENT_ID) esc.TIMER_WAIT NULL) AS statement_latency esc.LOCK_TIME AS lock_latency IF(isnull(esc.END_EVENT_ID) esc.TIMER_WAIT 0) AS sort_time FROM performance_schema.threads pps LEFT JOIN performance_schema.events_statements_current esc ON (pps.THREAD_ID = esc.THREAD_ID) LEFT JOIN performance_schema.session_connect_attrs conattr_pid ON ( conattr_pid.PROCESSLIST_ID = pps.PROCESSLIST_ID AND conattr_pid.ATTR_NAME = '_pid' ) WHERE pps.PROCESSLIST_I
NO QUERY
1014&1004
Query 1232 1195 statistics root@localhost db 0.8950ms 2.0000μs SELECT (SELECT VARIABLE_VALUE FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Uptime') AS "Uptime" MAX(CASE WHEN Metric = 'Threads Connected' THEN Value END) AS "Threads Connected" MAX(CASE WHEN Metric = 'Ongoing Query Count' THEN Value END) AS "Ongoing Query Count" MAX(CASE WHEN Metric = 'Ongoing Select Count' THEN Value END) AS "Ongoing Select Count" MAX(CASE WHEN Metric = 'Ongoing Insert Count' THEN Value END) AS "Ongoing Insert Count" MAX(CASE WHEN Metric = 'Ongoing Update Count' THEN Value END) AS "Ongoing Update Count" MAX(CASE WHEN Metric = 'Ongoing Delete Count' THEN Value END) AS "Ongoing Delete Count" FROM ( SELECT 'Threads Connected' AS Metric VARIABLE_VALUE AS Value FROM performance_schema.global_status WHERE VARIABLE_NAME = 'Threads_connected' UNION ALL SELECT 'Ongoing Query Count' AS Metric COUNT(*) AS Value FROM information_schema.processlist WHERE COMMAND <> 'Sleep' UNION ALL SELECT 'Ongoing Select
NO QUERY
